---
- name: 'ensure /data/k8s'
  file:
    state: 'directory'
    path: '{{ item }}'
    owner: 'bb'
    mode: '777'
  become: 'yes'
  with_items:
    - '/data/k8s'
    - '/etc/kubernetes/manifests'

- name: 'install kubernetes confs'
  template:
    src: '{{ item }}'
    dest: '/{{ item }}'
  become: 'yes'
  with_items:
    - 'etc/kubernetes/kube.conf'
    - 'etc/kubernetes/kubelet.conf'
    - 'etc/kubernetes/kube-proxy.conf'
    - 'etc/init/kubelet.conf'
    - 'etc/init/kube-proxy.conf'
  notify:
    - 'kubelet_restart'
    - 'kube_proxy_restart'

- name: 'install master pods'
  copy:
    src: '{{ item }}'
    dest: '/{{ item }}'
  become: 'yes'
  with_items:
    - 'etc/kubernetes/manifests/etcd.manifest'