---
- name: 'remove installed docker docker-engine or docker.io'
  apt:
    name: '{{ item }}'
    state: 'absent'
  with_items:
    - 'docker'
    - 'docker-engine'
    - 'docker.io'
  become: 'yes'

- name: 'update all packages to latest'
  apt:
    update_cache: 'yes'
  become: 'yes'

- name: 'update all packages to latest'
  shell: 'apt-get upgrade -y'
  become: 'yes'

- name: 'autoremove unused packages'
  apt:
    autoremove: 'yes'
    autoclean: 'yes'
  become: 'yes'

- name: 'install required packages'
  apt:
    name: '{{ item }}'
    state: 'latest'
  with_items:
    - 'linux-image-extra-{{ ansible_kernel }}'
    - 'linux-image-extra-virtual'
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'software-properties-common'
  become: 'yes'

- name: 'install docker apt-key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: 'present'
  become: 'yes'

- name: 'add docker apt repo'
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: 'present'
    filename: 'docker'
    update_cache: 'yes'
  become: 'yes'

- name: 'install docker-ce'
  apt:
    name: 'docker-ce'
    state: 'latest'
  become: 'yes'
